# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQ2YYO2qlozuDpt-roTtKqPni-GzAILG
"""

from flask import Flask, request, jsonify
import base64
from PIL import Image
import io
import numpy as np
from pyngrok import ngrok
from fastai.vision.all import *

app = Flask(__name__)

# Load your FastAI model
learn = load_learner('my_model.pkl')

def preprocess_image(image_b64):
    # Convert base64 image to bytes
    image_bytes = base64.b64decode(image_b64)

    # Convert bytes to PIL image
    image = Image.open(io.BytesIO(image_bytes))

    # Preprocess the image using FastAI's transforms
    image_fastai = PILImage.create(image)
    image_preprocessed = learn.dls.test_dl([image_fastai])[0][0]

    return image_preprocessed

@app.route('/predict', methods=['POST'])
def predict():
    try:
        # Get image data from the request body
        image_b64 = request.json.get('image', None)

        if image_b64 is None:
            return jsonify({'error': 'Image data not provided'}), 400

        # Preprocess the image and make predictions
        preprocessed_image = preprocess_image(image_b64)

        # Make predictions using the FastAI model
        prediction, _, _ = learn.predict(preprocessed_image)

        # Return predictions as JSON
        return jsonify({'predictions': str(prediction)})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Set up ngrok tunnel without using a configuration file
    # public_url = ngrok.connect(port='5000')
    # print('Ngrok Tunnel:', public_url)

    # Run the Flask app
    app.run()

pip install pyngrok

